/**:
  ros__parameters:
    min_longitudinal_offset: 2.7
    max_longitudinal_offset: 3.0
    min_lateral_offset: 0.9
    max_lateral_offset: -1.0
    min_height_offset: 1.2
    max_height_offset: 1.4
